### ISSUE TITLE
Document Bill of materials

### ISSUE THREAD

**Issue by goscommons** [goscommons/CNC-Plasma-Table#24]
Hey we are looking for people interested in filling the Bill of Materials. 
[You can do it here](https://docs.google.com/spreadsheets/d/1FX-_YOfYxhStZ97Nity5ue0BzQ9w-GSKeAwRe0n62uY/edit#gid=170551801)

**Comment by jurra** [comment]
Good idea. We were tryong that syaryegy yesterday at the workshop
