### ISSUE TITLE
Unused files should be deleted. File tree diagram needed

### ISSUE THREAD

**Issue by polemidis** [goscommons/CNC-Plasma-Table#3]
lots of files are not used anymore. One has to open all the sub-assemblies and modules to see what is not used anymore, as find any files that may be missing. (Most likely missing file will be OpenBuillds© cad models).

**Comment by jurra** [comment]
This can be closed right?

**Comment by polemidis** [comment]
No yet. There is a mess in the files. We need to make a tree diagram (like the one for the grapple) and then  keep the needed files. Most likely there will be deprecated files there.

**Comment by jurra** [comment]
Ok I understand
